# Run On PRs against all branches
pr:
  branches:
    include:
      - "*"
# Run on changes to main or dev or release branches
trigger:
  batch: true
  branches:
    include:
      - main
      - develop

pool:
  vmImage: "ubuntu-latest"

variables:
  bicepRegistryServiceConnection: "Bicep registry"
  azureServiceConnection: "Q42 Development"
  location: "westeurope"

  isMainBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: BuildInfra
    displayName: Build Infra
    jobs:
      - template: "azure-pipelines/infra-build.yml"
        parameters:
          workingDir: IaC-Bicep
          sourceFile: "main.bicep"
          artifactName: "Nuxt.Infra"

  - stage: DeployInfra
    displayName: Deploy Infra
    condition: and( succeeded() , eq(variables.isMainBranch, true) )
    dependsOn:
      - BuildInfra
    jobs:
      - template: "azure-pipelines/infra-deploy.yml"
        parameters:
          workingDir: $(Pipeline.Workspace)/Nuxt.Infra/IaC-Bicep
          environment: "main"
          variableGroupName: "main"

  - stage: BuildApp
    displayName: Build App
    jobs:
      - job: Build
        steps:
          - task: UseNode@1
            inputs:
              version: "18.x"

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                npm install -g @azure/static-web-apps-cli
                NITRO_PRESET=azure
                npm run build
              workingDirectory: src
