parameters:
- name: environment
  type: string

- name : workingDir
  type: string  

- name: variableGroupName
  type: string

  
jobs:
  - deployment: ${{ parameters.environment}}
    displayName: deploy bicep template 
    environment: ${{ parameters.environment}}
    variables:
    - group: ${{ parameters.variableGroupName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az --version
                az deployment sub create --location $(location) --template-file main.json --parameters parameters.main.json
              workingDirectory: ${{ parameters.workingDir }}



           
